services:
  backend-aspnet:
    build:
      context: ./ExpenseTracker
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend-react-aspnet:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend-aspnet